### ISSUE TITLE
clone出错

### ISSUE THREAD

**Issue by lszql** [AaNingNing/Sth-Matters#19]
error: invalid path 'Anonymity/04 - 社科答集/"骂娘"风气.md' 
fatal: unable to checkout working tree

**Comment by AaNingNing** [comment]
猜测故障原因为windows系统不支持文章标题中特殊字符，已删除。

**Comment by lszql** [comment]
> 猜测故障原因为windows系统不支持文章标题中特殊字符，已删除。

感谢，已解决！
