### ISSUE TITLE
建议添加README

### ISSUE THREAD

**Issue by zhanghuimeng** [AaNingNing/Sth-Matters#2]
建议把Drink me.md中的内容放到README.md里，这样仓库下面就会直接显示出文件内容，如下图所示，方便用户查看。

![图片](https://user-images.githubusercontent.com/26516581/154845821-8909821c-438b-46b7-89ea-44f882e9ef8c.png)

参见[Github Docs - About READMEs](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-readmes)

**Comment by AaNingNing** [comment]
已解决
