### ISSUE TITLE
Clone出错，windows不支持的英文双引号

### ISSUE THREAD

**Issue by DreamerDK** [AaNingNing/Sth-Matters#27]
错误代码：
```
invalid path '沙海拾金/泛讨论/泛讨论_"不比蒋小".md'
```

原因分析：
应该是因为windows不支持英文的双引号作为文件名，而仓库维护者使用的是Mac或linux平台，没有这个问题。

推荐方法：
1. 可将英文的双引号更改为中文的双引号，即可在不影响语义的情况下解决这一问题。
2. 可将双引号替换为单引号，虽稍不合语法，但也可解决该问题(也可以连用两个单引号使其视觉上构成双引号)，且不会因为字体原因造成混淆。

**Comment by AaNingNing** [comment]
感谢反馈，问题已修复。
