### ISSUE TITLE
clone出错了

### ISSUE THREAD

**Issue by fzfzfzzz** [AaNingNing/Sth-Matters#3]
error: invalid path 'Anonymity/04 - 社科答集/如何评价《睡前消息》409期?.md'

**Comment by nnnbbb** [comment]
error: invalid path 'Anonymity/04 - 社科答集/如何评价指挥网友声援A-SOUL讨伐字节控评引流的粉头“Karl Marx”是名作业没写完的高一学生?.md'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

**Comment by AaNingNing** [comment]
猜测故障原因为windows系统不支持文章标题中特殊字符，已删除。

**Comment by zanghuaren** [comment]
Cloning into 'C:\My File\我已到过那山顶\Sth-Matters'...
remote: Enumerating objects: 51239, done.        
remote: Counting objects: 100% (5741/5741), done.        
remote: Compressing objects: 100% (3499/3499), done.        
remote: Total 51239 (delta 2329), reused 5471 (delta 2154), pack-reused 45498        
Receiving objects: 100% (51239/51239), 244.02 MiB | 9.28 MiB/s, done.
Resolving deltas: 100% (42037/42037), done.
error: invalid path '7.24/修订/2023-07-28我们可以讽刺无神论者和有神论者吗?.md'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'


Would you like to retry cloning ?

这篇似乎有同样的问题，可以看下。
