### ISSUE TITLE
针对Md格式对转义符号的修正

### ISSUE THREAD

**Issue by wzj042** [AaNingNing/Sth-Matters#54]
在[如何管教写作业拖拉的孩子？](https://www.zhihu.com/question/308056561/answer/571941398)中

> obsidian://open?vault=Sth-Matters&file=Anonymity%2F01%20-%20%E5%AE%B6%E6%97%8F%E7%AD%94%E9%9B%86%2F%E6%8B%96%E6%8B%89%E6%9C%BA
> 协议原因无法识别为正确连接

“F*ck，这真的太费耳朵了。”

在obsidian中显示如下
![Snipaste_2023-12-18_11-24-00](https://github.com/AaNingNing/Sth-Matters/assets/40497125/9e6a3ec1-0069-4bae-bf78-9df66b87a516)

经
- 关闭插件重新渲染 
- 检验单独 \* 对文章字体的影响
- 关闭自动补全md语法后重新启动软件
 
的测试后，初步确认是obsidian自身特性，会将 \* 后的一段文本直接渲染为倾斜样式而并非遵守markdown标准：`*倾斜文本*` 

对此的解决方案可以是使用转义字符`\` 使 `*` 不被渲染
![Snipaste_2023-12-18_11-23-46](https://github.com/AaNingNing/Sth-Matters/assets/40497125/39fa718e-0852-4467-99df-958ba839db34)

修正效果如下（左边是修正后）

![Snipaste_2023-12-18_11-24-32](https://github.com/AaNingNing/Sth-Matters/assets/40497125/778f8e75-e856-4d5a-a1ec-78f56b39c064)

**Comment by AaNingNing** [comment]
感谢反馈，已修复。
