### ISSUE TITLE
阅读进度同步问题

### ISSUE THREAD

**Issue by charnameRed** [AaNingNing/Sth-Matters#57]
每次使用git更新时都会由于与您的阅读进度不同步导致冲突合并等问题

可否将 `.obsidian/app.json`和`.obsidian/workspace.json`两个文件列入`.gitignore`？这一方面可以避免相关的冲突，另一方面也避免由于`workspace.json`导致的您的阅读记录被泄露。

**Comment by AaNingNing** [comment]
感谢反馈，已采纳
