### ISSUE TITLE
【bug】重复添加的tag

### ISSUE THREAD

**Issue by wzj042** [AaNingNing/Sth-Matters#58]
[这一篇](https://github.com/AaNingNing/Sth-Matters/blob/main/%E3%80%90%E6%96%87%E7%AB%A0%E7%9B%AE%E5%BD%95%E3%80%91/%E3%80%905%20-%20%E7%A4%BE%E4%BC%9A%E7%A7%91%E5%AD%A6%E3%80%91/540%20-%20%E7%A4%BE%E4%BC%9A%E5%AD%A6/542%20-%20%E7%A4%BE%E4%BC%9A%E9%97%AE%E9%A2%98/%E7%A4%BE%E4%BC%9A%E8%B4%A3%E4%BB%BB%E4%B8%8E%E5%85%AC%E6%9D%83%E5%8A%9B/%E6%97%A0%E5%B8%B8.md)内容的tag出现了重复的`#1-家族/1B-处世/1-内务` tag

**Comment by AaNingNing** [comment]
感谢反馈，已修正
