### ISSUE TITLE
文章未添加原文链接

### ISSUE THREAD

**Issue by wzj042** [AaNingNing/Sth-Matters#60]
[该篇](https://github.com/AaNingNing/Sth-Matters/blob/main/%E3%80%90%E6%96%87%E7%AB%A0%E7%9B%AE%E5%BD%95%E3%80%91/%E3%80%904%20-%20%E5%BA%94%E7%94%A8%E7%A7%91%E5%AD%A6%E3%80%91/420%20-%20%E5%AE%B6%E6%94%BF/422%20-%20%E5%B1%85%E4%BD%8F%E7%8E%AF%E5%A2%83/%E5%86%85%E9%83%A8%E7%8E%AF%E5%A2%83/%E5%BE%AA%E7%8E%AF%E4%B9%B0%E5%8D%96.md)的顶部链接未添加，可能是疏忽了？

原文应该是这一篇：
[国内很多家庭不够整洁，深层次原因是什么？ - 9adgq的回答 - 知乎](https://www.zhihu.com/question/401778961/answer/1424763674)

**Comment by AaNingNing** [comment]
已修复，感谢反馈
